# Generated by Django 4.2.7 on 2024-03-19 03:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment_app', '0002_rename_teacher_add_change'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_change',
            new_name='Add_profile',
        ),
    ]
