# Generated by Django 4.2.7 on 2024-03-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0004_prodect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='equipment_images/')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='prodect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagefile/'),
        ),
    ]
