# Generated by Django 4.2.7 on 2024-03-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0005_equipment_prodect_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='priceday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pricehour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
