# Generated by Django 4.2.7 on 2024-03-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0006_equipment_priceday_equipment_pricehour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prodect',
        ),
    ]
