# Generated by Django 4.2.7 on 2024-03-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0007_delete_prodect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('nhours', models.IntegerField(blank=True, null=True)),
                ('ndays', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
