# Generated by Django 4.2.7 on 2024-03-25 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0008_buy_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_cart',
            old_name='image',
            new_name='prof',
        ),
        migrations.RemoveField(
            model_name='buy_cart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='buy_cart',
            name='place',
        ),
        migrations.AddField(
            model_name='buy_cart',
            name='book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buy_cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment_app.add_profile'),
        ),
        migrations.AddField(
            model_name='buy_cart',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment_app.equipment'),
        ),
    ]
