# Generated by Django 4.2.7 on 2024-03-25 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment_app', '0010_alter_buy_cart_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_cart',
            old_name='user1',
            new_name='equipment',
        ),
        migrations.AlterField(
            model_name='buy_cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
