# Generated by Django 4.2.7 on 2024-03-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0011_rename_user1_buy_cart_equipment_alter_buy_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_cart',
            name='ndate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
