# Generated by Django 4.2.7 on 2024-03-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0012_buy_cart_ndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_cart',
            name='prof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
