# Generated by Django 5.0.3 on 2024-04-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0017_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
