# Generated by Django 5.0.3 on 2024-04-14 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0021_reviews_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_app.add_profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
